### ISSUE TITLE
Error posting to mastodon

### ISSUE THREAD

**Issue by pietvanzoen** [jeffkreeftmeijer/dolphin#3]
Perhaps this is a configuration issue. I get the following error when posting to mastadon: 
```
2019-02-13T08:55:34.349276+00:00 heroku[router]: at=info method=POST path="/" host=dolphin-pvz.herokuapp.com request_id=ffb61aa6-f79a-4f3d-9fde-5579896565f0 fwd="93.117.244.82" dyno=web.1 connect=0ms service=2ms status=500 bytes=538 protocol=https

2019-02-13T08:55:34.349966+00:00 app[web.1]: 08:55:34.349 request_id=ffb61aa6-f79a-4f3d-9fde-5579896565f0 [info] POST /

2019-02-13T08:55:34.350685+00:00 app[web.1]: 08:55:34.350 request_id=ffb61aa6-f79a-4f3d-9fde-5579896565f0 [info] Converted error :function_clause to 500 response

2019-02-13T08:55:34.350789+00:00 app[web.1]: 08:55:34.350 request_id=ffb61aa6-f79a-4f3d-9fde-5579896565f0 [info] Sent 500 in 960µs

2019-02-13T08:55:34.351983+00:00 app[web.1]: 08:55:34.351 [error] #PID<0.475.0> running DolphinWeb.Endpoint (connection #PID<0.474.0>, stream id 1) terminated

2019-02-13T08:55:34.351985+00:00 app[web.1]: Server: dolphin-pvz.herokuapp.com:80 (http)

2019-02-13T08:55:34.351987+00:00 app[web.1]: Request: POST /

2019-02-13T08:55:34.351988+00:00 app[web.1]: ** (exit) an exception was raised:

2019-02-13T08:55:34.351990+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in Hunter.Api.HTTPClient.process_url/2

2019-02-13T08:55:34.351992+00:00 app[web.1]:         (hunter) lib/hunter/api/http_client.ex:354: Hunter.Api.HTTPClient.process_url("/api/v1/statuses", nil)

2019-02-13T08:55:34.351993+00:00 app[web.1]:         (hunter) lib/hunter/api/http_client.ex:158: Hunter.Api.HTTPClient.create_status/3

2019-02-13T08:55:34.351994+00:00 app[web.1]:         (dolphin) lib/dolphin/update/mastodon.ex:108: Dolphin.Update.Mastodon.post/1

2019-02-13T08:55:34.351996+00:00 app[web.1]:         (dolphin) lib/dolphin/update.ex:43: Dolphin.Update.post/1

2019-02-13T08:55:34.351997+00:00 app[web.1]:         (dolphin) lib/dolphin_web/controllers/update_controller.ex:45: DolphinWeb.UpdateController.create/2

2019-02-13T08:55:34.351998+00:00 app[web.1]:         (dolphin) lib/dolphin_web/controllers/update_controller.ex:1: DolphinWeb.UpdateController.action/2

2019-02-13T08:55:34.351999+00:00 app[web.1]:         (dolphin) lib/dolphin_web/controllers/update_controller.ex:1: DolphinWeb.UpdateController.phoenix_controller_pipeline/2

2019-02-13T08:55:34.352001+00:00 app[web.1]:         (dolphin) lib/dolphin_web/endpoint.ex:1: DolphinWeb.Endpoint.instrument/4
```

I have the following configuration.
```
MASTODON_BASE_URL=https://mastodon.social
MASTODON_BEARER_TOKEN=<secret>
```
I generated the bearer token via `https://mastodon.social/settings/applications` and created an app with full write access, just to be sure.

This error also prevents the post being pushed to github. 

Hope you can shine some light on this. Thanks!

**Comment by pietvanzoen** [comment]
Any ideas about this @jeffkreeftmeijer ? Been trying to figure it out, but hitting a wall. :/

**Comment by jeffkreeftmeijer** [comment]
Hey @pietvanzoen! I think I found what's causing this.

>Twitter and Mastodon credentials are optional, and Dolphin will only
post to configured services. When Dolphin is compiled without one of
these, the `(Twitter|Mastodon)configured?/0` function will return false,
preventing the update to be posted to that service.
>
>Currently, both modules use module attributes for quick access to the
credentials. In the case of Mastodon, the module holds a module named
`@base_url`, which is used by the `Hunter` library to know where to post
to.
>
>Since module attributes are set at compile time, compiling Dolphin
without Mastodon credentials and adding them later will result in the
`configured?/0` function to return `true` (as it checks the
configuration set when the app started), but posting to Mastodon will
produce a failure as the module attribute isn't available.
>
> The Heroku buildpack won't recompile the app for each deploy by default,
causing this to happen on Heroku too.

Could you try deploying the `rebuild` branch to Heroku to see if that solves your issue?

    $ git push heroku origin/rebuild:master

**Comment by pietvanzoen** [comment]
Success! Thanks!

https://github.com/pietvanzoen/updates/blob/master/2019-02-23-always-be-shipping-http-www.md
